services:
  db:
    image: postgres:15
    container_name: panda_db
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - panda_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 8

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: panda_backend
    restart: unless-stopped
    env_file:
      - ../.env
      - ../backend/.env
    environment:
      SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DJANGO_DEBUG}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - panda_static_data:/app/staticfiles

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: panda_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - panda_static_data:/vol/static:ro

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: panda_pgadmin
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    ports:
      - "8081:80"
    volumes:
      - panda_pgadmin_data:/var/lib/pgadmin

volumes:
  panda_db_data:
  panda_static_data:
  panda_pgadmin_data:
